Make command aware of possilbe retrieval of masked.tar file from VOSpace

diff --git a/scripts/daomop-stack-cmd b/scripts/daomop-stack-cmd
--- a/scripts/daomop-stack-cmd
+++ b/scripts/daomop-stack-cmd
@@ -41,20 +41,28 @@ else
     rate_max=3.5 && [ "$#" -gt "0" ] && rate_max=$1 && shift
 fi
  
-# get the psf file for this run
-mcp "${vos_uri}/psf_fwhm.txt" ./
-
 # pull the DIFF tar ball for this CCD from DIFFS/pointing directory on VOSpace.
-n_diffs=$(ls ${basedir}/rerun/${diff_rerun}/${exptype}/${pointing}/${filter}/DIFFEXP-*-${ccd}.* | wc -l)
-[ "${n_diffs}" -gt 10 ] || ( mcp -v "${vos_uri}/DIFFS/${pointing}/DIFF-${ccd}.*" ./  && tar xvf "DIFF-${ccd}.*" && rm "DIFF-${ccd}.*" || exit)
+n_diffs=$(ls ${basedir}/rerun/${diff_rerun}/${exptype}/${pointing}/${filter}/DIFFEXP-*-${ccd}_masked.* | wc -l)
+[ "${n_diffs}" -gt 10 ] || ( mcp -v "${vos_uri}/DIFFS/${pointing}/DIFF-${pointing}-${ccd}_masked.*" ./  && tar xvf "DIFF-${pointing}-${ccd}_masked.*" && rm "DIFF-${pointing}-${ccd}_masked.*" || echo "NO MASKED FILES" )
 
-# pull the DIFF tar ball for this CCD from DIFFS/pointing directory on VOSpace.
-n_corrs=$(ls ${basedir}/rerun/${plantOutputs}/${pointing}/${filter}/corr/CORR*-${ccd}.* | wc -l)
-[ "${n_corrs}" -gt 10 ] || (mcp -v "${vos_uri}/CORR/${pointing}/CORR-${ccd}.*" ./ && tar xvf "CORR-${ccd}.*" && rm "CORR-${ccd}.*" || exit)
+n_diffs=$(ls ${basedir}/rerun/${diff_rerun}/${exptype}/${pointing}/${filter}/DIFFEXP-*-${ccd}_masked.* | wc -l)
+if [ "${n_diffs}" -lt 10 ] 
+then
+   echo "Getting DIFFS and making MASKED version"
+   # get the psf file for this run
+   mcp "${vos_uri}/psf_fwhm.txt" ./
 
-# Build the MASKED versions of the files.
-for fullpath in ${basedir}/rerun/${diff_rerun}/${exptype}/${pointing}/${filter}/DIFFEXP-*-${ccd}.fits
-do
+   # pull the DIFF tar ball if _masked didn't exist for this CCD from DIFFS/pointing directory on VOSpace.
+   n_diffs=$(ls ${basedir}/rerun/${diff_rerun}/${exptype}/${pointing}/${filter}/DIFFEXP-*-${ccd}* | wc -l)
+   [ "${n_diffs}" -gt 10 ] || ( mcp -v "${vos_uri}/DIFFS/${pointing}/DIFF-${ccd}.*" ./  && tar xvf "DIFF-${ccd}.*" && rm "DIFF-${ccd}.*" || exit)
+
+   # pull the CORR tar ball for this CCD from DIFFS/pointing directory on VOSpace.
+   n_corrs=$(ls ${basedir}/rerun/${plantOutputs}/${pointing}/${filter}/corr/CORR*-${ccd}.* | wc -l)
+   [ "${n_corrs}" -gt 10 ] || (mcp -v "${vos_uri}/CORR/${pointing}/CORR-${ccd}.*" ./ && tar xvf "CORR-${ccd}.*" && rm "CORR-${ccd}.*" || exit)
+
+   # Build the MASKED versions of the files.
+   for fullpath in ${basedir}/rerun/${diff_rerun}/${exptype}/${pointing}/${filter}/DIFFEXP-*-${ccd}.fits
+   do
         masked="${fullpath%.*}_masked.fits"
         echo ${masked}
         [ -f ${masked} ] && continue
@@ -69,7 +77,20 @@ do
 		--visit ${visit} \
 		--psf-fwhm ${fwhm}  \
 		--log-level INFO || exit
-done
+   done
+
+   echo "Putting MASKED version to VOSpace"
+   tarfile=DIFF-${pointing}-${ccd}_masked.tar
+   masked_dir=${basedir}/rerun/${diff_rerun}/${exptype}/${pointing}/${filter}
+   tar czf ${tarfile} ${masked_dir}/*${ccd}_masked.fits  || break
+   [ -f ${tarfile} ] || (echo "FAILED MAKING TAR FILE" && break )
+   echo "Copying ${tarfile} to VOSpace"
+   vmkdir -p ${vos_uri}/DIFFS/${pointing}
+   mcp ${tarfile} ${vos_uri}/DIFFS/${pointing}/${tarfile} ||  (echo "FAILED COPY" && break)
+   echo "Cleaing up by deleting ${tarfile}"
+   rm ${tarfile} 
+
+fi 
 
 storage=${vos_uri}/STACKS_V3/${pointing}/${ccd}
 vmkdir -p ${storage}
